### ISSUE TITLE
Barrage Girdle, phase 1 - should it be phase 2?

### ISSUE THREAD

**Issue by memehammer** [itemization/itemization.info#1]
http://itemization.info/item/18681 Burial Shawl is listed as added in phase 2, (added 1.4)
http://itemization.info/item/18721 Barrage Girdle is listed as added in phase 1, (added 1.4)
I assume this is a bug since they both are added at the same time, but shows up in different phases

**Comment by itemization** [comment]
I couldn't reproduce it; I ran this search: `phase:1 slot:waist subtype:mail is:blue` and Barrage Girdle didn't show up. When I ran `phase:2 slot:waist subtype:mail is:blue` it did show up.

**Comment by memehammer** [comment]
Interesting, it **does work now.** Before the site went down I tried the search a few times where it showed Barrage Girdle as phase 1 despite being added in 1.4. Either I must have been blind somehow or the shutdown fixed the issue.
